name: Terraform Pipeline

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_aws_pub_key: ${{ secrets.AWS_PUB_KEY }}
      TF_VAR_azure_pub_key: ${{ secrets.AZURE_PUB_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      - run: terraform init 
      - run: terraform fmt
      - run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: validate
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_aws_pub_key: ${{ secrets.AWS_PUB_KEY }}
      TF_VAR_azure_pub_key: ${{ secrets.AZURE_PUB_KEY }}
    steps:
      - uses: actions/checkout@v4 
      - uses: hashicorp/setup-terraform@v3 
        with:
          terraform_version: 1.13.1 
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -out plan.out
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: plan.out

  apply:
    runs-on: ubuntu-latest
    needs: plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_aws_pub_key: ${{ secrets.AWS_PUB_KEY }}
      TF_VAR_azure_pub_key: ${{ secrets.AZURE_PUB_KEY }}
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .
      - run: terraform init
      - run: terraform apply -auto-approve plan.out

  destroy:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_aws_pub_key: ${{ secrets.AWS_PUB_KEY }}
      TF_VAR_azure_pub_key: ${{ secrets.AZURE_PUB_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      - run: terraform init
      - run: terraform destroy -auto-approve  
